//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identification_data
    {
        public int Serial_number { get; set; }
        public int Inventory_number { get; set; }
        public string Ip_adress { get; set; }
        public int Mac_adress { get; set; }
        public int Id { get; set; }
    
        public virtual Installed_equipment Installed_equipment { get; set; }
    }
}
