//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installed_equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installed_equipment()
        {
            this.Abonent = new HashSet<Abonent>();
            this.Identification_data = new HashSet<Identification_data>();
        }
    
        public int Serial_number { get; set; }
        public int Id_type { get; set; }
        public int Id_port { get; set; }
        public int Id_location { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonent> Abonent { get; set; }
        public virtual Equpment_type Equpment_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Identification_data> Identification_data { get; set; }
        public virtual Installation_location Installation_location { get; set; }
        public virtual Port Port { get; set; }
    }
}
