//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecome
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TelecomeDBEntities : DbContext
    {
        public TelecomeDBEntities()
            : base("name=TelecomeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent> Abonent { get; set; }
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Coordinates> Coordinates { get; set; }
        public virtual DbSet<Equpment_type> Equpment_type { get; set; }
        public virtual DbSet<Identification_data> Identification_data { get; set; }
        public virtual DbSet<Installation_location> Installation_location { get; set; }
        public virtual DbSet<Installed_equipment> Installed_equipment { get; set; }
        public virtual DbSet<Phone> Phone { get; set; }
        public virtual DbSet<Port> Port { get; set; }
        public virtual DbSet<Port_type> Port_type { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
