//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabric
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roll
    {
        public int Id { get; set; }
        public int Id_material { get; set; }
        public int Id_color { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Material Material { get; set; }
    }
}
